Welcome to Burlington UserR!
========================================================

Make a [doughnut plot](http://www.r-bloggers.com/doughnut-chart-in-r-with-googlevis/)

```{r doughnut}
dat <- data.frame(party=c("CDU", "FDP", "CSU", "SPD",
                          "The Left", "The Greens"),
                  members.of.parliament=c(193, 93, 44, 
                                          146, 76, 68))
```

Make a pie plot

```{r pie, echo=FALSE}
pie(dat$members.of.parliament, labels=dat$party)
```

Make a snazzy Google plot

```{r googleVis}
library(googleVis)
## Doughnut chart - a pie with a hole
doughnut <- gvisPieChart(dat, 
                      options=list(
                        width=500,
                        height=500,
                        slices="{0: {offset: 0.2},
                          1: {offset: 0.2},
                          2: {offset: 0.2}}",
                        title='German parliament 2009 - 2013 
                        (Goverment: CDU/FDP/CSU)',
                        legend='none',
                        colors="['black','orange', 'blue', 
                        'red', 'purple', 'green']",
                        pieSliceText='label',
                        pieHole=0.5),
                      chartid="doughnut")
plot(doughnut)
```

Here is some code `r print(dat)`
